// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Generated by `supabase gen types` — not hand-edited, don't lint.
  {
    ignores: ['app/types/database.ts']
  }
)
